version: 0.2 
 
env: 
  variables: 
    TF_VERSION: "1.1.2"
 
phases: 
 
  install: 
    commands: 
      - pwd
 
  build: 
    commands: 
      - pwd
      - ls
      - terraform init -no-color
      - terraform plan
 
  post_build: 
    commands: 
      - echo "Resources created by me"